In [187]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [188]:
df = pd.read_csv("C:/Users/user/Documents/GitHub/pandas-mini-projects/train.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [189]:
df.shape

(891, 12)

In [190]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

This shows that only 61.6% of passengers died during the sinking of the ship.

In [191]:
df[df['Survived'] == 0].shape[0] / df['Survived'].shape[0] * 100

61.61616161616161

Filters passengers that where older than 30 and where in first class.

In [192]:
df[(df['Age'] >= 30) & (df['Pclass'] == 1)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
30,31,0,1,"Uruchurtu, Don. Manuel E",male,40.0,0,0,PC 17601,27.7208,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,D17,S
867,868,0,1,"Roebling, Mr. Washington Augustus II",male,31.0,0,0,PC 17590,50.4958,A24,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C

Filters names that contain "Mrs" in them.

In [193]:
df[df['Name'].str.contains('Mrs')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q

Selects only four columns from the dataframe.

In [194]:
df[['Name', 'Age', 'Survived', 'Pclass']]

                                                  Name   Age  Survived  Pclass
0                              Braund, Mr. Owen Harris  22.0         0       3
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0         1       1
2                               Heikkinen, Miss. Laina  26.0         1       3
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0         1       1
4                             Allen, Mr. William Henry  35.0         0       3
..                                                 ...   ...       ...     ...
886                              Montvila, Rev. Juozas  27.0         0       2
887                       Graham, Miss. Margaret Edith  19.0         1       1
888           Johnston, Miss. Catherine Helen "Carrie"   NaN         0       3
889                              Behr, Mr. Karl Howell  26.0         1       1
890                                Dooley, Mr. Patrick  32.0         0       3

[891 rows x 4 columns]

Number of vissing values in each column, Filling it in with the median age, Dropping "Cabin" column because doesn't have any real valuem, Renaming "Pclass" to "Passenger_class" for more clarity, And adding "Age_Group" column that labels under eighteens as "Child" and "Adult" otherwise.

In [195]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [196]:
df['Age'] = df['Age'].fillna(df['Age'].median())

In [197]:
df.drop(columns=('Cabin'), inplace=True)

In [198]:
df.rename(columns={'Pclass':'Passenger_class'}, inplace=True)

In [199]:
def age_group_function(row):
    if row < 18:
        return ('Child')
    else:
        return ('Adult')

df['Age_Group'] = df['Age'].apply(age_group_function)
df

,PassengerId,Survived,Passenger_class,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Age_Group
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,Adult
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,Adult
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,Adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,Adult
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S,Adult
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S,Adult
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,S,Adult
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C,Adult
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q,Adult

In [200]:
df = df.dropna()

How many survived and how many died.

In [201]:
df['Survived'].value_counts()

Survived
0    549
1    340
Name: count, dtype: int64

Mean surviving chance per class.

In [202]:
df.groupby('Passenger_class')['Survived'].mean()

Passenger_class
1    0.626168
2    0.472826
3    0.242363
Name: Survived, dtype: float64

Mean age per gender.

In [203]:
df.groupby('Sex')['Age'].mean()

Sex
female    27.788462
male      30.140676
Name: Age, dtype: float64

Mean age and fare for every class.

In [204]:
df.groupby('Passenger_class')[['Age', 'Fare']].agg(['mean'])

                       Age       Fare
                      mean       mean
Passenger_class
1                36.688879  84.193516
2                29.765380  20.662183
3                25.932627  13.675550

Makes a pivot table showing the mean values compared to passenger class and sex.

In [205]:
df.pivot_table(index=('Passenger_class'), columns=('Sex'), values=('Survived'))

Sex                female      male
Passenger_class
1                0.967391  0.368852
2                0.921053  0.157407
3                0.500000  0.135447